Integration of CCPP-ized TJ2016 implementation
ESCOMP/CAM-SIMA pull request #271
Opened 2024-06-27 20:39 UTC by mwaxmonsky

Updates atmospheric_physics to the latest tag bringing in TJ2016 capability and additional changes needed in support of TJ2016.

Describe any changes made to build system: N/A

Describe any changes made to the namelist: N/A

List any changes to the defaults for the boundary datasets: N/A

Describe any substantial timing or memory changes: N/A

Code reviewed by: nusbaume, peverwhee

List all existing files that have been modified, old files eliminated, new files added and describe the changes:

M       Externals_CAM.cfg
- Updating to latest CCPP Framework needed for build.
- Updating to latest atmospheric_physics needed to bring in TJ2016.

M       src/control/cam_comp.F90
- Removing CAM suite and dynamic_constituents to match new API.

M       src/data/physconst.meta
- Updating two standard names.

M       src/data/registry.xml
A       src/dynamics/utils/hycoef.meta
- Exposing sum_of_sigma_pressure_hybrid_coordinate_a_coefficient_and_sigma_pressure_hybrid_coordinate_b_coefficient (etamid) to physics schemes.

M       src/dynamics/utils/hycoef.F90
- Updating lev, ilev, hybi, hyai to be read in by their standard names and updating PIO checks appropriately.

A       tools/generate_input_to_stdnames_update.py
- Adding new script to convert CSV file exported from standard names spreadsheet into the inputnames_dictionary.xml

M       tools/inputnames_to_stdnames.py
- Updating script to be tphysac/tphysbc aware to avoid duplicate standard names in snapshots.

M       tools/stdnames_to_inputnames_dictionary.xml
- Adding missing entry for standard_gravitational_acceleration.

M       cime_config/testdefs/testlist_cam.xml
D       cime_config/testdefs/testmods_dirs/cam/outfrq_held_suarez_izumi_nooutput/shell_commands
D       cime_config/testdefs/testmods_dirs/cam/outfrq_held_suarez_izumi_nooutput/user_nl_cam
D       cime_config/testdefs/testmods_dirs/cam/outfrq_kessler_izumi_nooutput/shell_commands
D       cime_config/testdefs/testmods_dirs/cam/outfrq_kessler_izumi_nooutput/user_nl_cam
A       cime_config/testdefs/testmods_dirs/cam/outfrq_tj2016_derecho_nooutput/shell_commands
A       cime_config/testdefs/testmods_dirs/cam/outfrq_tj2016_derecho_nooutput/user_nl_cam
- Adding derecho build test for tj2016, updating existing tests to build using both compilers (gnu and intel) and removing izumi tests based on discussion from 7/15/24 to simplify test setup process.

If there were any failures reported from running test_driver.sh on any test
platform, and checkin with these failures has been OK'd by the gatekeeper,
then copy the lines from the td.*.status files for the failed tests to the
appropriate machine below.  All failed tests must be justified.

derecho/intel/aux_cam
derecho/gnu/aux_cam
- All tests pass.

Summarize any changes to answers, i.e.,
- what code configurations: N/A
- what platforms/compilers: N/A
- nature of change (roundoff; larger than roundoff but same climate; new climate): N/A

2024-07-12 16:06 UTC, nusbaume requested changes
Looks good! I know it appears like a decent number of change requests but most of them should just be related to changing a particular error message.

Also, can the PR description be updated to include the following two things:

1.  The PR URL (so we can grab it in the git log if need be, unless Github will do this for us?)

2.  The results of the regression tests run on Derecho.

Instructions for how to run the tests can be found here:

https://github.com/ESCOMP/CAM-SIMA/wiki/CAM-SIMA-testing#regression-testing-manual

Note that you'll need to do it twice, once for GNU and once for Intel.  It might also be good to do snapshot test runs with the "official" snapshots that will live on Derecho here:

`/glade/campaign/cesm/community/amwg/sima_baselines/cam_sima_test_snapshots`

Mostly we just want to have a record that everything passed.

Thanks, and please let me know if you have any questions or concerns with any of my suggestions!

2024-07-12 20:44 UTC, mwaxmonsky commented on src/dynamics/utils/hycoef.F90
> +         call endrun(routine//': reading lev')
Updated!

2024-07-12 20:44 UTC, mwaxmonsky commented on src/dynamics/utils/hycoef.F90
> +         call endrun(routine//': reading ilev')
Updated!

2024-07-12 20:44 UTC, mwaxmonsky commented on src/dynamics/utils/hycoef.F90
> +         call endrun(routine//': reading hyai')
Updated!

2024-07-12 20:44 UTC, mwaxmonsky commented on src/dynamics/utils/hycoef.F90
> +         call endrun(routine//': reading hyam')
Updated!

2024-07-12 20:44 UTC, mwaxmonsky commented on src/dynamics/utils/hycoef.F90
> +         call endrun(routine//': reading hybi')
Updated!

2024-07-12 20:44 UTC, mwaxmonsky commented on src/dynamics/utils/hycoef.F90
> +         call endrun(routine//': reading hybm')
Updated!

2024-07-12 20:45 UTC, mwaxmonsky commented on tools/generate_input_to_stdnames_update.py
> +                #   raise Exception(f"Found duplicate standard name {standardname_match.string} on line {csvdata.line_num}")
Removed!

2024-07-12 20:45 UTC, mwaxmonsky commented on tools/generate_input_to_stdnames_update.py
> +    parser.add_argument('--current-map', type=str, default='stdnames_to_inputnames_dictionary.xml', help='')
Removed!  This was a hold over from the previous implementation that was not working.

2024-07-12 20:45 UTC, mwaxmonsky commented on tools/inputnames_to_stdnames.py
> +                        metavar='tphysac or tphybs group - REQUIRED',
Updated!

2024-07-15 16:40 UTC, mwaxmonsky commented on src/dynamics/utils/hycoef.F90
>     ierr = pio_get_var(File, hyai_desc, hyai)
Added!

2024-07-15 16:51 UTC, mwaxmonsky commented on tools/inputnames_to_stdnames.py
> +                        help='Group to convert to stdandard names')
Good catch!  Was really confused by this one for a sec and then noticed the `not` in front of the string check.

2024-07-15 16:52 UTC, mwaxmonsky commented on Externals_CAM.cfg
> +tag = CPF_0.2.057
Updated!

2024-07-15 18:05 UTC, nusbaume approved these changes
Looks great, thanks @mwaxmonsky!

2024-07-19 02:30 UTC, peverwhee requested changes
two more tiny error checks!

2024-07-19 14:20 UTC, mwaxmonsky commented on src/dynamics/utils/hycoef.F90
>     ierr = PIO_Inq_dimlen(File, lev_dimid, flev)
Added!

2024-07-19 14:20 UTC, mwaxmonsky commented on src/dynamics/utils/hycoef.F90
>     ierr = PIO_Inq_dimlen(File, lev_dimid, filev)
Added!

2024-07-19 16:53 UTC, peverwhee approved these changes
thanks!

2024-07-23 16:16 UTC, peverwhee commented
@mwaxmonsky I ran a clean check-out of CAM-SIMA with your updates and git-fleximod worked well. I did run into this bug - https://github.com/ESCOMP/CAM-SIMA/pull/280 (introduced by me), but I vote for merging this PR!

2024-07-23 17:25 UTC, merged