Update regression tests to run!
ESCOMP/CAM-SIMA pull request #323
Opened 2024-11-14 18:48 UTC by peverwhee

Tag name (required for release branches): sima0_00_001
Originator(s): peverwhee

Description (include the issue title, and the keyword ['closes', 'fixes', 'resolves'] followed by the issue number):

Updates the regression tests to actually run and compare against previous baselines.

Describe any changes made to build system: 
- added new compset FCAM7 that exercises the cam7 physics suites
- updated config_pes.xml for ne3 grid

Describe any changes made to the namelist:
- updated namelist defaults for ne3 grid (though these are currently unused; using analytic_ic until the SE dycore is updated)

List any changes to the defaults for the input datasets (e.g. boundary datasets):

List all files MOVED and why:
cime_config/testdefs/testmods_dirs/cam/outfrq_kessler_mpas_derecho_nooutput/user_nl_cam
cime_config/testdefs/testmods_dirs/cam/outfrq_kessler_mpas_derecho_nooutput/shell_commands
cime_config/testdefs/testmods_dirs/cam/outfrq_held_suarez_derecho_nooutput/shell_commands
cime_config/testdefs/testmods_dirs/cam/outfrq_held_suarez_derecho_nooutput/user_nl_cam
cime_config/testdefs/testmods_dirs/cam/outfrq_kessler_derecho_nooutput/shell_commands
cime_config/testdefs/testmods_dirs/cam/outfrq_kessler_derecho_nooutput/user_nl_cam
cime_config/testdefs/testmods_dirs/cam/outfrq_tj2016_derecho_nooutput/user_nl_cam
cime_config/testdefs/testmods_dirs/cam/outfrq_tj2016_derecho_nooutput/shell_commands
- removed "nooutput" from directory name

cime_config/testdefs/testmods_dirs/cam/outfrq_kessler_se_cslam_derecho_nooutput/user_nl_cam
cime_config/testdefs/testmods_dirs/cam/outfrq_kessler_se_cslam_derecho_nooutput/shell_commands
- moved to outfrq_se_sclam/*

List all files added and what they do:
A cime_config/config_archive.xml
- brought over from CAM so tests will run

List all existing files that have been modified, and describe the changes: 
(Helpful git command: `git diff --name-status development...<your_branch_name>`)
M cime_config/config_component.xml
- added FCAM7 configuration

M cime_config/config_compset.xml
- added FCAM7 compset

M cime_config/config_pes.xml
- modified for ne3 grid

M cime_config/namelist_definition_cam.xml
- added ne3 grid defaults

M cime_config/testdefs/testlist_cam.xml
- added FHS94 and FTJ16 SE CSLAM tests
- modified existing FKESSLER SE CSLAM test to use ne5

M src/dynamics/tests/namelist_definition_analy_ic.xml
- use held-suarez initial conditions by default (not "none")

M test/system/archive_baseline.sh
- update to add a symlink to the ${baseline_dir}/latest_${CAM_FC} directory for easier test_driver usage
- add flag to turn off symlink addition

M test/system/test_driver.sh
- use ${baseline_dir}/latest_${CAM_FC} by default
- add flag to turn off default usage (no baseline comparison)

If there are new failures (compared to the `test/existing-test-failures.txt` file),
have them OK'd by the gatekeeper, note them here, and add them to the file.
If there are baseline differences, include the test and the reason for the
diff. What is the nature of the change? Roundoff?

derecho/intel/aux_sima:
SMS_Ln2.mpasa480_mpasa480.FKESSLER.derecho_intel.cam-outfrq_kessler_mpas_derecho
- will fail until MPAS is fully integrated

derecho/gnu/aux_sima:
SMS_Ln2.mpasa480_mpasa480.FKESSLER.derecho_gnu.cam-outfrq_kessler_mpas_derecho
- will fail until MPAS is fully integrated

If this changes climate describe any run(s) done to evaluate the new
climate in enough detail that it(they) could be reproduced: n/a

CAM-SIMA date used for the baseline comparison tests if different than latest: first baselines!

2024-11-18 18:15 UTC, nusbaume requested changes
Thanks for getting the tests going!  I do have some change requests (which is mostly me backpedaling from previous things I asked you to do, sorry!), but hopefully it won't be too hard to implement.  Of course please let me know if that is not the case.  Thanks again!

2024-11-21 18:28 UTC, peverwhee commented on cime_config/testdefs/testmods_dirs/cam/outfrq_held_suarez_derecho/user_nl_cam
> +hist_add_inst_fields;h2: Q, T
Currently, "ZM" is geopotential height (wrt surface) in CAM-SIMA - should this be "Z3" instead?

2024-11-21 18:45 UTC, nusbaume commented on cime_config/testdefs/testmods_dirs/cam/outfrq_held_suarez_derecho/user_nl_cam
> +hist_add_inst_fields;h2: Q, T
Whoops, sorry, I meant `ZM`, I just knew it as `Z3` from CAM (but I never liked the name because I have no idea what the "3" means).  Thanks!

2024-11-22 00:07 UTC, peverwhee commented on cime_config/config_component.xml
> +      <value compset="_CAM70">--physics-suites cam7 --analytic_ic</value>
moved & added a new outfrq_se_cslam_analy_ic test case directory

2024-11-22 00:07 UTC, peverwhee commented on cime_config/testdefs/testlist_cam.xml
> +      <option name="comment">Test for Moist Held-Suarez physics</option>
updated!

2024-11-22 00:07 UTC, peverwhee commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FKESSLER" grid="mpasa480_mpasa480" name="SMS_Ln2" testmods="cam/outfrq_kessler_mpas_derecho">
updated!

2024-11-22 00:07 UTC, peverwhee commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FCAM7" grid="ne5pg3_ne5pg3_mg37" name="SMS_Ln2" testmods="cam/outfrq_se_cslam">
updated!

2024-11-22 00:07 UTC, peverwhee commented on cime_config/testdefs/testlist_cam.xml
> +      <option name="comment">Test for SE-CSLAM dycore (with CAM7 physics)</option>
updated!

2024-11-22 00:07 UTC, peverwhee commented on cime_config/testdefs/testmods_dirs/cam/outfrq_kessler_mpas_derecho/user_nl_cam
> +hist_add_inst_fields;h2: Q, T
added fields!

2024-11-22 00:07 UTC, peverwhee commented on cime_config/testdefs/testmods_dirs/cam/outfrq_se_cslam/user_nl_cam
> +hist_add_inst_fields;h1: T, Q, PS
added fields!

2024-11-22 00:08 UTC, peverwhee commented on cime_config/testdefs/testmods_dirs/cam/outfrq_held_suarez_derecho/user_nl_cam
> +hist_add_inst_fields;h2: Q, T
changed!

2024-11-22 00:08 UTC, peverwhee commented on src/dynamics/tests/namelist_definition_analy_ic.xml
> +      <value>held_suarez_1994</value>
switched back to none and updated the cam7 user_nl_cam file

2024-11-22 00:08 UTC, peverwhee commented on test/system/archive_baseline.sh
> +        until thenext baselines are established. If you'd like to not create the symlink (e.g.
fixed!

2024-11-22 00:08 UTC, peverwhee commented on test/system/archive_baseline.sh
>  	This is an example for izumi.
updated!

2024-11-22 00:08 UTC, peverwhee commented on test/system/archive_baseline.sh
> +    chmod_cmd=""
no reason i can think of - changed!

2024-11-22 00:09 UTC, peverwhee commented on test/system/archive_baseline.sh
> +        ln -s $root_baselinedir/$cam_tag $root_baselinedir/latest_${CAM_FC,,}
thanks! that does indeed work! changed!

2024-11-22 00:10 UTC, peverwhee commented
@nusbaume thanks for your review. I also added the NL option to endrun on ncdata_check failures (and added it to the kessler test, which is currently the only one that has very small diffs) - if you could take a look at that, that'd be great!

2024-11-22 15:35 UTC, nusbaume requested changes
Almost there!   Just two last requests.

2024-11-22 17:14 UTC, peverwhee commented on cime_config/testdefs/testlist_cam.xml
> +  <test compset="FKESSLER" grid="mpasa480_mpasa480" name="SMS_Ln2" testmods="cam/outfrq_kessler_mpas_derecho">
it was! thanks! fixed now.

2024-11-22 17:14 UTC, peverwhee commented on src/data/write_init_files.py
> +    outfile.write("end if", 2)
Good idea - moved!

2024-11-22 17:44 UTC, nusbaume approved these changes
Looks great to me now.  Thanks again!

2024-11-22 17:47 UTC, nusbaume commented
Also forgot to mention that you can close issue #229 once this PR is merged.  It might also be worth "addressing" issue #230 as well (we can close that one once we have all of snapshot checks working).  Thanks!

2024-11-25 22:27 UTC, mwaxmonsky approved these changes
Looks great @peverwhee, thanks for getting this added!

One minor whitespace fix I think might be needed but nothing worth holding up this PR.

2024-11-27 19:19 UTC, peverwhee commented on test/system/test_driver.sh
> +	--no-bl-compare ) baseline_default=false
Can I ask why this whitespace change? I'm not a bash expert, but it does match the rest of the arguments

2024-12-02 17:32 UTC, peverwhee commented on test/system/test_driver.sh
> +	--no-bl-compare ) baseline_default=false
turns out it was a "tab" whitespace - fixed!

2024-12-09 16:37 UTC, merged